/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tbims.rpc.entity;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 终端信息、网点信息
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-08-21")
public class SYS_CLIENT_OUTLET implements org.apache.thrift.TBase<SYS_CLIENT_OUTLET, SYS_CLIENT_OUTLET._Fields>, java.io.Serializable, Cloneable, Comparable<SYS_CLIENT_OUTLET> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SYS_CLIENT_OUTLET");

  private static final org.apache.thrift.protocol.TField CLIENT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("clientId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField CLIENT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("clientName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CLIENT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("clientType", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField REGION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("regionId", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField IP_ADDR_FIELD_DESC = new org.apache.thrift.protocol.TField("ipAddr", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField STAT_FIELD_DESC = new org.apache.thrift.protocol.TField("stat", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("token", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField RUN_STAT_FIELD_DESC = new org.apache.thrift.protocol.TField("runStat", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField REPORT_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("reportTime", org.apache.thrift.protocol.TType.I64, (short)10);
  private static final org.apache.thrift.protocol.TField OUTLET_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("outletId", org.apache.thrift.protocol.TType.I64, (short)11);
  private static final org.apache.thrift.protocol.TField OUTLET_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("outletName", org.apache.thrift.protocol.TType.STRING, (short)12);
  private static final org.apache.thrift.protocol.TField LOCATION_FIELD_DESC = new org.apache.thrift.protocol.TField("location", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField LEADER_FIELD_DESC = new org.apache.thrift.protocol.TField("leader", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField TEL_FIELD_DESC = new org.apache.thrift.protocol.TField("tel", org.apache.thrift.protocol.TType.STRING, (short)15);
  private static final org.apache.thrift.protocol.TField OUTLET_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("outletType", org.apache.thrift.protocol.TType.STRING, (short)16);
  private static final org.apache.thrift.protocol.TField ORG_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("orgId", org.apache.thrift.protocol.TType.STRING, (short)17);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SYS_CLIENT_OUTLETStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SYS_CLIENT_OUTLETTupleSchemeFactory();

  public long clientId; // required
  public java.lang.String clientName; // required
  public java.lang.String clientType; // optional
  public long regionId; // optional
  public java.lang.String ipAddr; // optional
  public java.lang.String port; // optional
  public java.lang.String stat; // optional
  public java.lang.String token; // optional
  public java.lang.String runStat; // optional
  public long reportTime; // optional
  public long outletId; // optional
  public java.lang.String outletName; // optional
  public java.lang.String location; // optional
  public java.lang.String leader; // optional
  public java.lang.String tel; // optional
  public java.lang.String outletType; // optional
  public java.lang.String orgId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CLIENT_ID((short)1, "clientId"),
    CLIENT_NAME((short)2, "clientName"),
    CLIENT_TYPE((short)3, "clientType"),
    REGION_ID((short)4, "regionId"),
    IP_ADDR((short)5, "ipAddr"),
    PORT((short)6, "port"),
    STAT((short)7, "stat"),
    TOKEN((short)8, "token"),
    RUN_STAT((short)9, "runStat"),
    REPORT_TIME((short)10, "reportTime"),
    OUTLET_ID((short)11, "outletId"),
    OUTLET_NAME((short)12, "outletName"),
    LOCATION((short)13, "location"),
    LEADER((short)14, "leader"),
    TEL((short)15, "tel"),
    OUTLET_TYPE((short)16, "outletType"),
    ORG_ID((short)17, "orgId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CLIENT_ID
          return CLIENT_ID;
        case 2: // CLIENT_NAME
          return CLIENT_NAME;
        case 3: // CLIENT_TYPE
          return CLIENT_TYPE;
        case 4: // REGION_ID
          return REGION_ID;
        case 5: // IP_ADDR
          return IP_ADDR;
        case 6: // PORT
          return PORT;
        case 7: // STAT
          return STAT;
        case 8: // TOKEN
          return TOKEN;
        case 9: // RUN_STAT
          return RUN_STAT;
        case 10: // REPORT_TIME
          return REPORT_TIME;
        case 11: // OUTLET_ID
          return OUTLET_ID;
        case 12: // OUTLET_NAME
          return OUTLET_NAME;
        case 13: // LOCATION
          return LOCATION;
        case 14: // LEADER
          return LEADER;
        case 15: // TEL
          return TEL;
        case 16: // OUTLET_TYPE
          return OUTLET_TYPE;
        case 17: // ORG_ID
          return ORG_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CLIENTID_ISSET_ID = 0;
  private static final int __REGIONID_ISSET_ID = 1;
  private static final int __REPORTTIME_ISSET_ID = 2;
  private static final int __OUTLETID_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.CLIENT_TYPE,_Fields.REGION_ID,_Fields.IP_ADDR,_Fields.PORT,_Fields.STAT,_Fields.TOKEN,_Fields.RUN_STAT,_Fields.REPORT_TIME,_Fields.OUTLET_ID,_Fields.OUTLET_NAME,_Fields.LOCATION,_Fields.LEADER,_Fields.TEL,_Fields.OUTLET_TYPE,_Fields.ORG_ID};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CLIENT_ID, new org.apache.thrift.meta_data.FieldMetaData("clientId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CLIENT_NAME, new org.apache.thrift.meta_data.FieldMetaData("clientName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLIENT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("clientType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REGION_ID, new org.apache.thrift.meta_data.FieldMetaData("regionId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.IP_ADDR, new org.apache.thrift.meta_data.FieldMetaData("ipAddr", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STAT, new org.apache.thrift.meta_data.FieldMetaData("stat", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TOKEN, new org.apache.thrift.meta_data.FieldMetaData("token", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RUN_STAT, new org.apache.thrift.meta_data.FieldMetaData("runStat", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REPORT_TIME, new org.apache.thrift.meta_data.FieldMetaData("reportTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OUTLET_ID, new org.apache.thrift.meta_data.FieldMetaData("outletId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OUTLET_NAME, new org.apache.thrift.meta_data.FieldMetaData("outletName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LOCATION, new org.apache.thrift.meta_data.FieldMetaData("location", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LEADER, new org.apache.thrift.meta_data.FieldMetaData("leader", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TEL, new org.apache.thrift.meta_data.FieldMetaData("tel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OUTLET_TYPE, new org.apache.thrift.meta_data.FieldMetaData("outletType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ORG_ID, new org.apache.thrift.meta_data.FieldMetaData("orgId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SYS_CLIENT_OUTLET.class, metaDataMap);
  }

  public SYS_CLIENT_OUTLET() {
  }

  public SYS_CLIENT_OUTLET(
    long clientId,
    java.lang.String clientName)
  {
    this();
    this.clientId = clientId;
    setClientIdIsSet(true);
    this.clientName = clientName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SYS_CLIENT_OUTLET(SYS_CLIENT_OUTLET other) {
    __isset_bitfield = other.__isset_bitfield;
    this.clientId = other.clientId;
    if (other.isSetClientName()) {
      this.clientName = other.clientName;
    }
    if (other.isSetClientType()) {
      this.clientType = other.clientType;
    }
    this.regionId = other.regionId;
    if (other.isSetIpAddr()) {
      this.ipAddr = other.ipAddr;
    }
    if (other.isSetPort()) {
      this.port = other.port;
    }
    if (other.isSetStat()) {
      this.stat = other.stat;
    }
    if (other.isSetToken()) {
      this.token = other.token;
    }
    if (other.isSetRunStat()) {
      this.runStat = other.runStat;
    }
    this.reportTime = other.reportTime;
    this.outletId = other.outletId;
    if (other.isSetOutletName()) {
      this.outletName = other.outletName;
    }
    if (other.isSetLocation()) {
      this.location = other.location;
    }
    if (other.isSetLeader()) {
      this.leader = other.leader;
    }
    if (other.isSetTel()) {
      this.tel = other.tel;
    }
    if (other.isSetOutletType()) {
      this.outletType = other.outletType;
    }
    if (other.isSetOrgId()) {
      this.orgId = other.orgId;
    }
  }

  public SYS_CLIENT_OUTLET deepCopy() {
    return new SYS_CLIENT_OUTLET(this);
  }

  @Override
  public void clear() {
    setClientIdIsSet(false);
    this.clientId = 0;
    this.clientName = null;
    this.clientType = null;
    setRegionIdIsSet(false);
    this.regionId = 0;
    this.ipAddr = null;
    this.port = null;
    this.stat = null;
    this.token = null;
    this.runStat = null;
    setReportTimeIsSet(false);
    this.reportTime = 0;
    setOutletIdIsSet(false);
    this.outletId = 0;
    this.outletName = null;
    this.location = null;
    this.leader = null;
    this.tel = null;
    this.outletType = null;
    this.orgId = null;
  }

  public long getClientId() {
    return this.clientId;
  }

  public SYS_CLIENT_OUTLET setClientId(long clientId) {
    this.clientId = clientId;
    setClientIdIsSet(true);
    return this;
  }

  public void unsetClientId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CLIENTID_ISSET_ID);
  }

  /** Returns true if field clientId is set (has been assigned a value) and false otherwise */
  public boolean isSetClientId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CLIENTID_ISSET_ID);
  }

  public void setClientIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CLIENTID_ISSET_ID, value);
  }

  public java.lang.String getClientName() {
    return this.clientName;
  }

  public SYS_CLIENT_OUTLET setClientName(java.lang.String clientName) {
    this.clientName = clientName;
    return this;
  }

  public void unsetClientName() {
    this.clientName = null;
  }

  /** Returns true if field clientName is set (has been assigned a value) and false otherwise */
  public boolean isSetClientName() {
    return this.clientName != null;
  }

  public void setClientNameIsSet(boolean value) {
    if (!value) {
      this.clientName = null;
    }
  }

  public java.lang.String getClientType() {
    return this.clientType;
  }

  public SYS_CLIENT_OUTLET setClientType(java.lang.String clientType) {
    this.clientType = clientType;
    return this;
  }

  public void unsetClientType() {
    this.clientType = null;
  }

  /** Returns true if field clientType is set (has been assigned a value) and false otherwise */
  public boolean isSetClientType() {
    return this.clientType != null;
  }

  public void setClientTypeIsSet(boolean value) {
    if (!value) {
      this.clientType = null;
    }
  }

  public long getRegionId() {
    return this.regionId;
  }

  public SYS_CLIENT_OUTLET setRegionId(long regionId) {
    this.regionId = regionId;
    setRegionIdIsSet(true);
    return this;
  }

  public void unsetRegionId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REGIONID_ISSET_ID);
  }

  /** Returns true if field regionId is set (has been assigned a value) and false otherwise */
  public boolean isSetRegionId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REGIONID_ISSET_ID);
  }

  public void setRegionIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REGIONID_ISSET_ID, value);
  }

  public java.lang.String getIpAddr() {
    return this.ipAddr;
  }

  public SYS_CLIENT_OUTLET setIpAddr(java.lang.String ipAddr) {
    this.ipAddr = ipAddr;
    return this;
  }

  public void unsetIpAddr() {
    this.ipAddr = null;
  }

  /** Returns true if field ipAddr is set (has been assigned a value) and false otherwise */
  public boolean isSetIpAddr() {
    return this.ipAddr != null;
  }

  public void setIpAddrIsSet(boolean value) {
    if (!value) {
      this.ipAddr = null;
    }
  }

  public java.lang.String getPort() {
    return this.port;
  }

  public SYS_CLIENT_OUTLET setPort(java.lang.String port) {
    this.port = port;
    return this;
  }

  public void unsetPort() {
    this.port = null;
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return this.port != null;
  }

  public void setPortIsSet(boolean value) {
    if (!value) {
      this.port = null;
    }
  }

  public java.lang.String getStat() {
    return this.stat;
  }

  public SYS_CLIENT_OUTLET setStat(java.lang.String stat) {
    this.stat = stat;
    return this;
  }

  public void unsetStat() {
    this.stat = null;
  }

  /** Returns true if field stat is set (has been assigned a value) and false otherwise */
  public boolean isSetStat() {
    return this.stat != null;
  }

  public void setStatIsSet(boolean value) {
    if (!value) {
      this.stat = null;
    }
  }

  public java.lang.String getToken() {
    return this.token;
  }

  public SYS_CLIENT_OUTLET setToken(java.lang.String token) {
    this.token = token;
    return this;
  }

  public void unsetToken() {
    this.token = null;
  }

  /** Returns true if field token is set (has been assigned a value) and false otherwise */
  public boolean isSetToken() {
    return this.token != null;
  }

  public void setTokenIsSet(boolean value) {
    if (!value) {
      this.token = null;
    }
  }

  public java.lang.String getRunStat() {
    return this.runStat;
  }

  public SYS_CLIENT_OUTLET setRunStat(java.lang.String runStat) {
    this.runStat = runStat;
    return this;
  }

  public void unsetRunStat() {
    this.runStat = null;
  }

  /** Returns true if field runStat is set (has been assigned a value) and false otherwise */
  public boolean isSetRunStat() {
    return this.runStat != null;
  }

  public void setRunStatIsSet(boolean value) {
    if (!value) {
      this.runStat = null;
    }
  }

  public long getReportTime() {
    return this.reportTime;
  }

  public SYS_CLIENT_OUTLET setReportTime(long reportTime) {
    this.reportTime = reportTime;
    setReportTimeIsSet(true);
    return this;
  }

  public void unsetReportTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REPORTTIME_ISSET_ID);
  }

  /** Returns true if field reportTime is set (has been assigned a value) and false otherwise */
  public boolean isSetReportTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REPORTTIME_ISSET_ID);
  }

  public void setReportTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REPORTTIME_ISSET_ID, value);
  }

  public long getOutletId() {
    return this.outletId;
  }

  public SYS_CLIENT_OUTLET setOutletId(long outletId) {
    this.outletId = outletId;
    setOutletIdIsSet(true);
    return this;
  }

  public void unsetOutletId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OUTLETID_ISSET_ID);
  }

  /** Returns true if field outletId is set (has been assigned a value) and false otherwise */
  public boolean isSetOutletId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OUTLETID_ISSET_ID);
  }

  public void setOutletIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OUTLETID_ISSET_ID, value);
  }

  public java.lang.String getOutletName() {
    return this.outletName;
  }

  public SYS_CLIENT_OUTLET setOutletName(java.lang.String outletName) {
    this.outletName = outletName;
    return this;
  }

  public void unsetOutletName() {
    this.outletName = null;
  }

  /** Returns true if field outletName is set (has been assigned a value) and false otherwise */
  public boolean isSetOutletName() {
    return this.outletName != null;
  }

  public void setOutletNameIsSet(boolean value) {
    if (!value) {
      this.outletName = null;
    }
  }

  public java.lang.String getLocation() {
    return this.location;
  }

  public SYS_CLIENT_OUTLET setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  public void unsetLocation() {
    this.location = null;
  }

  /** Returns true if field location is set (has been assigned a value) and false otherwise */
  public boolean isSetLocation() {
    return this.location != null;
  }

  public void setLocationIsSet(boolean value) {
    if (!value) {
      this.location = null;
    }
  }

  public java.lang.String getLeader() {
    return this.leader;
  }

  public SYS_CLIENT_OUTLET setLeader(java.lang.String leader) {
    this.leader = leader;
    return this;
  }

  public void unsetLeader() {
    this.leader = null;
  }

  /** Returns true if field leader is set (has been assigned a value) and false otherwise */
  public boolean isSetLeader() {
    return this.leader != null;
  }

  public void setLeaderIsSet(boolean value) {
    if (!value) {
      this.leader = null;
    }
  }

  public java.lang.String getTel() {
    return this.tel;
  }

  public SYS_CLIENT_OUTLET setTel(java.lang.String tel) {
    this.tel = tel;
    return this;
  }

  public void unsetTel() {
    this.tel = null;
  }

  /** Returns true if field tel is set (has been assigned a value) and false otherwise */
  public boolean isSetTel() {
    return this.tel != null;
  }

  public void setTelIsSet(boolean value) {
    if (!value) {
      this.tel = null;
    }
  }

  public java.lang.String getOutletType() {
    return this.outletType;
  }

  public SYS_CLIENT_OUTLET setOutletType(java.lang.String outletType) {
    this.outletType = outletType;
    return this;
  }

  public void unsetOutletType() {
    this.outletType = null;
  }

  /** Returns true if field outletType is set (has been assigned a value) and false otherwise */
  public boolean isSetOutletType() {
    return this.outletType != null;
  }

  public void setOutletTypeIsSet(boolean value) {
    if (!value) {
      this.outletType = null;
    }
  }

  public java.lang.String getOrgId() {
    return this.orgId;
  }

  public SYS_CLIENT_OUTLET setOrgId(java.lang.String orgId) {
    this.orgId = orgId;
    return this;
  }

  public void unsetOrgId() {
    this.orgId = null;
  }

  /** Returns true if field orgId is set (has been assigned a value) and false otherwise */
  public boolean isSetOrgId() {
    return this.orgId != null;
  }

  public void setOrgIdIsSet(boolean value) {
    if (!value) {
      this.orgId = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case CLIENT_ID:
      if (value == null) {
        unsetClientId();
      } else {
        setClientId((java.lang.Long)value);
      }
      break;

    case CLIENT_NAME:
      if (value == null) {
        unsetClientName();
      } else {
        setClientName((java.lang.String)value);
      }
      break;

    case CLIENT_TYPE:
      if (value == null) {
        unsetClientType();
      } else {
        setClientType((java.lang.String)value);
      }
      break;

    case REGION_ID:
      if (value == null) {
        unsetRegionId();
      } else {
        setRegionId((java.lang.Long)value);
      }
      break;

    case IP_ADDR:
      if (value == null) {
        unsetIpAddr();
      } else {
        setIpAddr((java.lang.String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((java.lang.String)value);
      }
      break;

    case STAT:
      if (value == null) {
        unsetStat();
      } else {
        setStat((java.lang.String)value);
      }
      break;

    case TOKEN:
      if (value == null) {
        unsetToken();
      } else {
        setToken((java.lang.String)value);
      }
      break;

    case RUN_STAT:
      if (value == null) {
        unsetRunStat();
      } else {
        setRunStat((java.lang.String)value);
      }
      break;

    case REPORT_TIME:
      if (value == null) {
        unsetReportTime();
      } else {
        setReportTime((java.lang.Long)value);
      }
      break;

    case OUTLET_ID:
      if (value == null) {
        unsetOutletId();
      } else {
        setOutletId((java.lang.Long)value);
      }
      break;

    case OUTLET_NAME:
      if (value == null) {
        unsetOutletName();
      } else {
        setOutletName((java.lang.String)value);
      }
      break;

    case LOCATION:
      if (value == null) {
        unsetLocation();
      } else {
        setLocation((java.lang.String)value);
      }
      break;

    case LEADER:
      if (value == null) {
        unsetLeader();
      } else {
        setLeader((java.lang.String)value);
      }
      break;

    case TEL:
      if (value == null) {
        unsetTel();
      } else {
        setTel((java.lang.String)value);
      }
      break;

    case OUTLET_TYPE:
      if (value == null) {
        unsetOutletType();
      } else {
        setOutletType((java.lang.String)value);
      }
      break;

    case ORG_ID:
      if (value == null) {
        unsetOrgId();
      } else {
        setOrgId((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CLIENT_ID:
      return getClientId();

    case CLIENT_NAME:
      return getClientName();

    case CLIENT_TYPE:
      return getClientType();

    case REGION_ID:
      return getRegionId();

    case IP_ADDR:
      return getIpAddr();

    case PORT:
      return getPort();

    case STAT:
      return getStat();

    case TOKEN:
      return getToken();

    case RUN_STAT:
      return getRunStat();

    case REPORT_TIME:
      return getReportTime();

    case OUTLET_ID:
      return getOutletId();

    case OUTLET_NAME:
      return getOutletName();

    case LOCATION:
      return getLocation();

    case LEADER:
      return getLeader();

    case TEL:
      return getTel();

    case OUTLET_TYPE:
      return getOutletType();

    case ORG_ID:
      return getOrgId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CLIENT_ID:
      return isSetClientId();
    case CLIENT_NAME:
      return isSetClientName();
    case CLIENT_TYPE:
      return isSetClientType();
    case REGION_ID:
      return isSetRegionId();
    case IP_ADDR:
      return isSetIpAddr();
    case PORT:
      return isSetPort();
    case STAT:
      return isSetStat();
    case TOKEN:
      return isSetToken();
    case RUN_STAT:
      return isSetRunStat();
    case REPORT_TIME:
      return isSetReportTime();
    case OUTLET_ID:
      return isSetOutletId();
    case OUTLET_NAME:
      return isSetOutletName();
    case LOCATION:
      return isSetLocation();
    case LEADER:
      return isSetLeader();
    case TEL:
      return isSetTel();
    case OUTLET_TYPE:
      return isSetOutletType();
    case ORG_ID:
      return isSetOrgId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SYS_CLIENT_OUTLET)
      return this.equals((SYS_CLIENT_OUTLET)that);
    return false;
  }

  public boolean equals(SYS_CLIENT_OUTLET that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_clientId = true;
    boolean that_present_clientId = true;
    if (this_present_clientId || that_present_clientId) {
      if (!(this_present_clientId && that_present_clientId))
        return false;
      if (this.clientId != that.clientId)
        return false;
    }

    boolean this_present_clientName = true && this.isSetClientName();
    boolean that_present_clientName = true && that.isSetClientName();
    if (this_present_clientName || that_present_clientName) {
      if (!(this_present_clientName && that_present_clientName))
        return false;
      if (!this.clientName.equals(that.clientName))
        return false;
    }

    boolean this_present_clientType = true && this.isSetClientType();
    boolean that_present_clientType = true && that.isSetClientType();
    if (this_present_clientType || that_present_clientType) {
      if (!(this_present_clientType && that_present_clientType))
        return false;
      if (!this.clientType.equals(that.clientType))
        return false;
    }

    boolean this_present_regionId = true && this.isSetRegionId();
    boolean that_present_regionId = true && that.isSetRegionId();
    if (this_present_regionId || that_present_regionId) {
      if (!(this_present_regionId && that_present_regionId))
        return false;
      if (this.regionId != that.regionId)
        return false;
    }

    boolean this_present_ipAddr = true && this.isSetIpAddr();
    boolean that_present_ipAddr = true && that.isSetIpAddr();
    if (this_present_ipAddr || that_present_ipAddr) {
      if (!(this_present_ipAddr && that_present_ipAddr))
        return false;
      if (!this.ipAddr.equals(that.ipAddr))
        return false;
    }

    boolean this_present_port = true && this.isSetPort();
    boolean that_present_port = true && that.isSetPort();
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (!this.port.equals(that.port))
        return false;
    }

    boolean this_present_stat = true && this.isSetStat();
    boolean that_present_stat = true && that.isSetStat();
    if (this_present_stat || that_present_stat) {
      if (!(this_present_stat && that_present_stat))
        return false;
      if (!this.stat.equals(that.stat))
        return false;
    }

    boolean this_present_token = true && this.isSetToken();
    boolean that_present_token = true && that.isSetToken();
    if (this_present_token || that_present_token) {
      if (!(this_present_token && that_present_token))
        return false;
      if (!this.token.equals(that.token))
        return false;
    }

    boolean this_present_runStat = true && this.isSetRunStat();
    boolean that_present_runStat = true && that.isSetRunStat();
    if (this_present_runStat || that_present_runStat) {
      if (!(this_present_runStat && that_present_runStat))
        return false;
      if (!this.runStat.equals(that.runStat))
        return false;
    }

    boolean this_present_reportTime = true && this.isSetReportTime();
    boolean that_present_reportTime = true && that.isSetReportTime();
    if (this_present_reportTime || that_present_reportTime) {
      if (!(this_present_reportTime && that_present_reportTime))
        return false;
      if (this.reportTime != that.reportTime)
        return false;
    }

    boolean this_present_outletId = true && this.isSetOutletId();
    boolean that_present_outletId = true && that.isSetOutletId();
    if (this_present_outletId || that_present_outletId) {
      if (!(this_present_outletId && that_present_outletId))
        return false;
      if (this.outletId != that.outletId)
        return false;
    }

    boolean this_present_outletName = true && this.isSetOutletName();
    boolean that_present_outletName = true && that.isSetOutletName();
    if (this_present_outletName || that_present_outletName) {
      if (!(this_present_outletName && that_present_outletName))
        return false;
      if (!this.outletName.equals(that.outletName))
        return false;
    }

    boolean this_present_location = true && this.isSetLocation();
    boolean that_present_location = true && that.isSetLocation();
    if (this_present_location || that_present_location) {
      if (!(this_present_location && that_present_location))
        return false;
      if (!this.location.equals(that.location))
        return false;
    }

    boolean this_present_leader = true && this.isSetLeader();
    boolean that_present_leader = true && that.isSetLeader();
    if (this_present_leader || that_present_leader) {
      if (!(this_present_leader && that_present_leader))
        return false;
      if (!this.leader.equals(that.leader))
        return false;
    }

    boolean this_present_tel = true && this.isSetTel();
    boolean that_present_tel = true && that.isSetTel();
    if (this_present_tel || that_present_tel) {
      if (!(this_present_tel && that_present_tel))
        return false;
      if (!this.tel.equals(that.tel))
        return false;
    }

    boolean this_present_outletType = true && this.isSetOutletType();
    boolean that_present_outletType = true && that.isSetOutletType();
    if (this_present_outletType || that_present_outletType) {
      if (!(this_present_outletType && that_present_outletType))
        return false;
      if (!this.outletType.equals(that.outletType))
        return false;
    }

    boolean this_present_orgId = true && this.isSetOrgId();
    boolean that_present_orgId = true && that.isSetOrgId();
    if (this_present_orgId || that_present_orgId) {
      if (!(this_present_orgId && that_present_orgId))
        return false;
      if (!this.orgId.equals(that.orgId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(clientId);

    hashCode = hashCode * 8191 + ((isSetClientName()) ? 131071 : 524287);
    if (isSetClientName())
      hashCode = hashCode * 8191 + clientName.hashCode();

    hashCode = hashCode * 8191 + ((isSetClientType()) ? 131071 : 524287);
    if (isSetClientType())
      hashCode = hashCode * 8191 + clientType.hashCode();

    hashCode = hashCode * 8191 + ((isSetRegionId()) ? 131071 : 524287);
    if (isSetRegionId())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(regionId);

    hashCode = hashCode * 8191 + ((isSetIpAddr()) ? 131071 : 524287);
    if (isSetIpAddr())
      hashCode = hashCode * 8191 + ipAddr.hashCode();

    hashCode = hashCode * 8191 + ((isSetPort()) ? 131071 : 524287);
    if (isSetPort())
      hashCode = hashCode * 8191 + port.hashCode();

    hashCode = hashCode * 8191 + ((isSetStat()) ? 131071 : 524287);
    if (isSetStat())
      hashCode = hashCode * 8191 + stat.hashCode();

    hashCode = hashCode * 8191 + ((isSetToken()) ? 131071 : 524287);
    if (isSetToken())
      hashCode = hashCode * 8191 + token.hashCode();

    hashCode = hashCode * 8191 + ((isSetRunStat()) ? 131071 : 524287);
    if (isSetRunStat())
      hashCode = hashCode * 8191 + runStat.hashCode();

    hashCode = hashCode * 8191 + ((isSetReportTime()) ? 131071 : 524287);
    if (isSetReportTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(reportTime);

    hashCode = hashCode * 8191 + ((isSetOutletId()) ? 131071 : 524287);
    if (isSetOutletId())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(outletId);

    hashCode = hashCode * 8191 + ((isSetOutletName()) ? 131071 : 524287);
    if (isSetOutletName())
      hashCode = hashCode * 8191 + outletName.hashCode();

    hashCode = hashCode * 8191 + ((isSetLocation()) ? 131071 : 524287);
    if (isSetLocation())
      hashCode = hashCode * 8191 + location.hashCode();

    hashCode = hashCode * 8191 + ((isSetLeader()) ? 131071 : 524287);
    if (isSetLeader())
      hashCode = hashCode * 8191 + leader.hashCode();

    hashCode = hashCode * 8191 + ((isSetTel()) ? 131071 : 524287);
    if (isSetTel())
      hashCode = hashCode * 8191 + tel.hashCode();

    hashCode = hashCode * 8191 + ((isSetOutletType()) ? 131071 : 524287);
    if (isSetOutletType())
      hashCode = hashCode * 8191 + outletType.hashCode();

    hashCode = hashCode * 8191 + ((isSetOrgId()) ? 131071 : 524287);
    if (isSetOrgId())
      hashCode = hashCode * 8191 + orgId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SYS_CLIENT_OUTLET other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetClientId()).compareTo(other.isSetClientId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClientId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientId, other.clientId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetClientName()).compareTo(other.isSetClientName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClientName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientName, other.clientName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetClientType()).compareTo(other.isSetClientType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClientType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientType, other.clientType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRegionId()).compareTo(other.isSetRegionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.regionId, other.regionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIpAddr()).compareTo(other.isSetIpAddr());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIpAddr()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ipAddr, other.ipAddr);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPort()).compareTo(other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStat()).compareTo(other.isSetStat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stat, other.stat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetToken()).compareTo(other.isSetToken());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToken()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.token, other.token);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRunStat()).compareTo(other.isSetRunStat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRunStat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.runStat, other.runStat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReportTime()).compareTo(other.isSetReportTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReportTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reportTime, other.reportTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOutletId()).compareTo(other.isSetOutletId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutletId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outletId, other.outletId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOutletName()).compareTo(other.isSetOutletName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutletName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outletName, other.outletName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLocation()).compareTo(other.isSetLocation());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocation()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.location, other.location);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLeader()).compareTo(other.isSetLeader());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLeader()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.leader, other.leader);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTel()).compareTo(other.isSetTel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tel, other.tel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOutletType()).compareTo(other.isSetOutletType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutletType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outletType, other.outletType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOrgId()).compareTo(other.isSetOrgId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrgId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.orgId, other.orgId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SYS_CLIENT_OUTLET(");
    boolean first = true;

    sb.append("clientId:");
    sb.append(this.clientId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("clientName:");
    if (this.clientName == null) {
      sb.append("null");
    } else {
      sb.append(this.clientName);
    }
    first = false;
    if (isSetClientType()) {
      if (!first) sb.append(", ");
      sb.append("clientType:");
      if (this.clientType == null) {
        sb.append("null");
      } else {
        sb.append(this.clientType);
      }
      first = false;
    }
    if (isSetRegionId()) {
      if (!first) sb.append(", ");
      sb.append("regionId:");
      sb.append(this.regionId);
      first = false;
    }
    if (isSetIpAddr()) {
      if (!first) sb.append(", ");
      sb.append("ipAddr:");
      if (this.ipAddr == null) {
        sb.append("null");
      } else {
        sb.append(this.ipAddr);
      }
      first = false;
    }
    if (isSetPort()) {
      if (!first) sb.append(", ");
      sb.append("port:");
      if (this.port == null) {
        sb.append("null");
      } else {
        sb.append(this.port);
      }
      first = false;
    }
    if (isSetStat()) {
      if (!first) sb.append(", ");
      sb.append("stat:");
      if (this.stat == null) {
        sb.append("null");
      } else {
        sb.append(this.stat);
      }
      first = false;
    }
    if (isSetToken()) {
      if (!first) sb.append(", ");
      sb.append("token:");
      if (this.token == null) {
        sb.append("null");
      } else {
        sb.append(this.token);
      }
      first = false;
    }
    if (isSetRunStat()) {
      if (!first) sb.append(", ");
      sb.append("runStat:");
      if (this.runStat == null) {
        sb.append("null");
      } else {
        sb.append(this.runStat);
      }
      first = false;
    }
    if (isSetReportTime()) {
      if (!first) sb.append(", ");
      sb.append("reportTime:");
      sb.append(this.reportTime);
      first = false;
    }
    if (isSetOutletId()) {
      if (!first) sb.append(", ");
      sb.append("outletId:");
      sb.append(this.outletId);
      first = false;
    }
    if (isSetOutletName()) {
      if (!first) sb.append(", ");
      sb.append("outletName:");
      if (this.outletName == null) {
        sb.append("null");
      } else {
        sb.append(this.outletName);
      }
      first = false;
    }
    if (isSetLocation()) {
      if (!first) sb.append(", ");
      sb.append("location:");
      if (this.location == null) {
        sb.append("null");
      } else {
        sb.append(this.location);
      }
      first = false;
    }
    if (isSetLeader()) {
      if (!first) sb.append(", ");
      sb.append("leader:");
      if (this.leader == null) {
        sb.append("null");
      } else {
        sb.append(this.leader);
      }
      first = false;
    }
    if (isSetTel()) {
      if (!first) sb.append(", ");
      sb.append("tel:");
      if (this.tel == null) {
        sb.append("null");
      } else {
        sb.append(this.tel);
      }
      first = false;
    }
    if (isSetOutletType()) {
      if (!first) sb.append(", ");
      sb.append("outletType:");
      if (this.outletType == null) {
        sb.append("null");
      } else {
        sb.append(this.outletType);
      }
      first = false;
    }
    if (isSetOrgId()) {
      if (!first) sb.append(", ");
      sb.append("orgId:");
      if (this.orgId == null) {
        sb.append("null");
      } else {
        sb.append(this.orgId);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'clientId' because it's a primitive and you chose the non-beans generator.
    if (clientName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'clientName' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SYS_CLIENT_OUTLETStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SYS_CLIENT_OUTLETStandardScheme getScheme() {
      return new SYS_CLIENT_OUTLETStandardScheme();
    }
  }

  private static class SYS_CLIENT_OUTLETStandardScheme extends org.apache.thrift.scheme.StandardScheme<SYS_CLIENT_OUTLET> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SYS_CLIENT_OUTLET struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CLIENT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.clientId = iprot.readI64();
              struct.setClientIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CLIENT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clientName = iprot.readString();
              struct.setClientNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CLIENT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clientType = iprot.readString();
              struct.setClientTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REGION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.regionId = iprot.readI64();
              struct.setRegionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IP_ADDR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ipAddr = iprot.readString();
              struct.setIpAddrIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.port = iprot.readString();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // STAT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.stat = iprot.readString();
              struct.setStatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // TOKEN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.token = iprot.readString();
              struct.setTokenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // RUN_STAT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.runStat = iprot.readString();
              struct.setRunStatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // REPORT_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.reportTime = iprot.readI64();
              struct.setReportTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // OUTLET_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.outletId = iprot.readI64();
              struct.setOutletIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // OUTLET_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.outletName = iprot.readString();
              struct.setOutletNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // LOCATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.location = iprot.readString();
              struct.setLocationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // LEADER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.leader = iprot.readString();
              struct.setLeaderIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // TEL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tel = iprot.readString();
              struct.setTelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // OUTLET_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.outletType = iprot.readString();
              struct.setOutletTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // ORG_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.orgId = iprot.readString();
              struct.setOrgIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetClientId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'clientId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SYS_CLIENT_OUTLET struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CLIENT_ID_FIELD_DESC);
      oprot.writeI64(struct.clientId);
      oprot.writeFieldEnd();
      if (struct.clientName != null) {
        oprot.writeFieldBegin(CLIENT_NAME_FIELD_DESC);
        oprot.writeString(struct.clientName);
        oprot.writeFieldEnd();
      }
      if (struct.clientType != null) {
        if (struct.isSetClientType()) {
          oprot.writeFieldBegin(CLIENT_TYPE_FIELD_DESC);
          oprot.writeString(struct.clientType);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetRegionId()) {
        oprot.writeFieldBegin(REGION_ID_FIELD_DESC);
        oprot.writeI64(struct.regionId);
        oprot.writeFieldEnd();
      }
      if (struct.ipAddr != null) {
        if (struct.isSetIpAddr()) {
          oprot.writeFieldBegin(IP_ADDR_FIELD_DESC);
          oprot.writeString(struct.ipAddr);
          oprot.writeFieldEnd();
        }
      }
      if (struct.port != null) {
        if (struct.isSetPort()) {
          oprot.writeFieldBegin(PORT_FIELD_DESC);
          oprot.writeString(struct.port);
          oprot.writeFieldEnd();
        }
      }
      if (struct.stat != null) {
        if (struct.isSetStat()) {
          oprot.writeFieldBegin(STAT_FIELD_DESC);
          oprot.writeString(struct.stat);
          oprot.writeFieldEnd();
        }
      }
      if (struct.token != null) {
        if (struct.isSetToken()) {
          oprot.writeFieldBegin(TOKEN_FIELD_DESC);
          oprot.writeString(struct.token);
          oprot.writeFieldEnd();
        }
      }
      if (struct.runStat != null) {
        if (struct.isSetRunStat()) {
          oprot.writeFieldBegin(RUN_STAT_FIELD_DESC);
          oprot.writeString(struct.runStat);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetReportTime()) {
        oprot.writeFieldBegin(REPORT_TIME_FIELD_DESC);
        oprot.writeI64(struct.reportTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetOutletId()) {
        oprot.writeFieldBegin(OUTLET_ID_FIELD_DESC);
        oprot.writeI64(struct.outletId);
        oprot.writeFieldEnd();
      }
      if (struct.outletName != null) {
        if (struct.isSetOutletName()) {
          oprot.writeFieldBegin(OUTLET_NAME_FIELD_DESC);
          oprot.writeString(struct.outletName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.location != null) {
        if (struct.isSetLocation()) {
          oprot.writeFieldBegin(LOCATION_FIELD_DESC);
          oprot.writeString(struct.location);
          oprot.writeFieldEnd();
        }
      }
      if (struct.leader != null) {
        if (struct.isSetLeader()) {
          oprot.writeFieldBegin(LEADER_FIELD_DESC);
          oprot.writeString(struct.leader);
          oprot.writeFieldEnd();
        }
      }
      if (struct.tel != null) {
        if (struct.isSetTel()) {
          oprot.writeFieldBegin(TEL_FIELD_DESC);
          oprot.writeString(struct.tel);
          oprot.writeFieldEnd();
        }
      }
      if (struct.outletType != null) {
        if (struct.isSetOutletType()) {
          oprot.writeFieldBegin(OUTLET_TYPE_FIELD_DESC);
          oprot.writeString(struct.outletType);
          oprot.writeFieldEnd();
        }
      }
      if (struct.orgId != null) {
        if (struct.isSetOrgId()) {
          oprot.writeFieldBegin(ORG_ID_FIELD_DESC);
          oprot.writeString(struct.orgId);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SYS_CLIENT_OUTLETTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SYS_CLIENT_OUTLETTupleScheme getScheme() {
      return new SYS_CLIENT_OUTLETTupleScheme();
    }
  }

  private static class SYS_CLIENT_OUTLETTupleScheme extends org.apache.thrift.scheme.TupleScheme<SYS_CLIENT_OUTLET> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SYS_CLIENT_OUTLET struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.clientId);
      oprot.writeString(struct.clientName);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetClientType()) {
        optionals.set(0);
      }
      if (struct.isSetRegionId()) {
        optionals.set(1);
      }
      if (struct.isSetIpAddr()) {
        optionals.set(2);
      }
      if (struct.isSetPort()) {
        optionals.set(3);
      }
      if (struct.isSetStat()) {
        optionals.set(4);
      }
      if (struct.isSetToken()) {
        optionals.set(5);
      }
      if (struct.isSetRunStat()) {
        optionals.set(6);
      }
      if (struct.isSetReportTime()) {
        optionals.set(7);
      }
      if (struct.isSetOutletId()) {
        optionals.set(8);
      }
      if (struct.isSetOutletName()) {
        optionals.set(9);
      }
      if (struct.isSetLocation()) {
        optionals.set(10);
      }
      if (struct.isSetLeader()) {
        optionals.set(11);
      }
      if (struct.isSetTel()) {
        optionals.set(12);
      }
      if (struct.isSetOutletType()) {
        optionals.set(13);
      }
      if (struct.isSetOrgId()) {
        optionals.set(14);
      }
      oprot.writeBitSet(optionals, 15);
      if (struct.isSetClientType()) {
        oprot.writeString(struct.clientType);
      }
      if (struct.isSetRegionId()) {
        oprot.writeI64(struct.regionId);
      }
      if (struct.isSetIpAddr()) {
        oprot.writeString(struct.ipAddr);
      }
      if (struct.isSetPort()) {
        oprot.writeString(struct.port);
      }
      if (struct.isSetStat()) {
        oprot.writeString(struct.stat);
      }
      if (struct.isSetToken()) {
        oprot.writeString(struct.token);
      }
      if (struct.isSetRunStat()) {
        oprot.writeString(struct.runStat);
      }
      if (struct.isSetReportTime()) {
        oprot.writeI64(struct.reportTime);
      }
      if (struct.isSetOutletId()) {
        oprot.writeI64(struct.outletId);
      }
      if (struct.isSetOutletName()) {
        oprot.writeString(struct.outletName);
      }
      if (struct.isSetLocation()) {
        oprot.writeString(struct.location);
      }
      if (struct.isSetLeader()) {
        oprot.writeString(struct.leader);
      }
      if (struct.isSetTel()) {
        oprot.writeString(struct.tel);
      }
      if (struct.isSetOutletType()) {
        oprot.writeString(struct.outletType);
      }
      if (struct.isSetOrgId()) {
        oprot.writeString(struct.orgId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SYS_CLIENT_OUTLET struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.clientId = iprot.readI64();
      struct.setClientIdIsSet(true);
      struct.clientName = iprot.readString();
      struct.setClientNameIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(15);
      if (incoming.get(0)) {
        struct.clientType = iprot.readString();
        struct.setClientTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.regionId = iprot.readI64();
        struct.setRegionIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.ipAddr = iprot.readString();
        struct.setIpAddrIsSet(true);
      }
      if (incoming.get(3)) {
        struct.port = iprot.readString();
        struct.setPortIsSet(true);
      }
      if (incoming.get(4)) {
        struct.stat = iprot.readString();
        struct.setStatIsSet(true);
      }
      if (incoming.get(5)) {
        struct.token = iprot.readString();
        struct.setTokenIsSet(true);
      }
      if (incoming.get(6)) {
        struct.runStat = iprot.readString();
        struct.setRunStatIsSet(true);
      }
      if (incoming.get(7)) {
        struct.reportTime = iprot.readI64();
        struct.setReportTimeIsSet(true);
      }
      if (incoming.get(8)) {
        struct.outletId = iprot.readI64();
        struct.setOutletIdIsSet(true);
      }
      if (incoming.get(9)) {
        struct.outletName = iprot.readString();
        struct.setOutletNameIsSet(true);
      }
      if (incoming.get(10)) {
        struct.location = iprot.readString();
        struct.setLocationIsSet(true);
      }
      if (incoming.get(11)) {
        struct.leader = iprot.readString();
        struct.setLeaderIsSet(true);
      }
      if (incoming.get(12)) {
        struct.tel = iprot.readString();
        struct.setTelIsSet(true);
      }
      if (incoming.get(13)) {
        struct.outletType = iprot.readString();
        struct.setOutletTypeIsSet(true);
      }
      if (incoming.get(14)) {
        struct.orgId = iprot.readString();
        struct.setOrgIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

