/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace tbims.rpc.entity
{

  /// <summary>
  /// 配送申请审核明细表
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class STR_DELIVERY_APPLY_DETAIL : TBase
  {
    private long _examNum;

    /// <summary>
    /// 申请审核明细主键
    /// </summary>
    public string ApplyExamId { get; set; }

    /// <summary>
    /// 申请编号
    /// </summary>
    public string ApplyId { get; set; }

    /// <summary>
    /// 票种编号
    /// </summary>
    public string TicketTypeId { get; set; }

    /// <summary>
    /// 申请数量
    /// </summary>
    public long ApplyNum { get; set; }

    /// <summary>
    /// 审核数量
    /// </summary>
    public long ExamNum
    {
      get
      {
        return _examNum;
      }
      set
      {
        __isset.examNum = true;
        this._examNum = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool examNum;
    }

    public STR_DELIVERY_APPLY_DETAIL() {
    }

    public STR_DELIVERY_APPLY_DETAIL(string applyExamId, string applyId, string ticketTypeId, long applyNum) : this() {
      this.ApplyExamId = applyExamId;
      this.ApplyId = applyId;
      this.TicketTypeId = ticketTypeId;
      this.ApplyNum = applyNum;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_applyExamId = false;
        bool isset_applyId = false;
        bool isset_ticketTypeId = false;
        bool isset_applyNum = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                ApplyExamId = iprot.ReadString();
                isset_applyExamId = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                ApplyId = iprot.ReadString();
                isset_applyId = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                TicketTypeId = iprot.ReadString();
                isset_ticketTypeId = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I64) {
                ApplyNum = iprot.ReadI64();
                isset_applyNum = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.I64) {
                ExamNum = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_applyExamId)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_applyId)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_ticketTypeId)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
        if (!isset_applyNum)
          throw new TProtocolException(TProtocolException.INVALID_DATA);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("STR_DELIVERY_APPLY_DETAIL");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        field.Name = "applyExamId";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ApplyExamId);
        oprot.WriteFieldEnd();
        field.Name = "applyId";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ApplyId);
        oprot.WriteFieldEnd();
        field.Name = "ticketTypeId";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(TicketTypeId);
        oprot.WriteFieldEnd();
        field.Name = "applyNum";
        field.Type = TType.I64;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(ApplyNum);
        oprot.WriteFieldEnd();
        if (__isset.examNum) {
          field.Name = "examNum";
          field.Type = TType.I64;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ExamNum);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("STR_DELIVERY_APPLY_DETAIL(");
      __sb.Append(", ApplyExamId: ");
      __sb.Append(ApplyExamId);
      __sb.Append(", ApplyId: ");
      __sb.Append(ApplyId);
      __sb.Append(", TicketTypeId: ");
      __sb.Append(TicketTypeId);
      __sb.Append(", ApplyNum: ");
      __sb.Append(ApplyNum);
      if (__isset.examNum) {
        __sb.Append(", ExamNum: ");
        __sb.Append(ExamNum);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
